function [noisyImageDN, imageDN] = shot_noise(image, exposureTime, electronFlux, ...
                              fullWell, gain)
arguments (Input)
    image (:,:,:) {mustBeA(image, ["uint8", "uint16"])}
    exposureTime (1,1) double {mustBePositive}
    electronFlux (1,1) double {mustBePositive}
    fullWell (1,1) double {mustBePositive}
    gain (1,1) double {mustBePositive}
end

arguments (Output)
    noisyImageDN (:,:,:) double
    imageDN (:,:,:) double
end

% Normalize image between 0 and 1
imageNormalized = double(image)/double(intmax(class(image)));

% Calculate true per-pixel electron flux
electronFlux = imageNormalized .* electronFlux;

% Calculate electrons generated by each pixel
expectedElectrons = electronFlux .* exposureTime;

% Poisson electron generation (valid for N>10)
noise = sqrt(expectedElectrons) .* randn(size(expectedElectrons));
noisyElectrons = expectedElectrons + noise;

% Clip electrons to physical limits
noisyElectrons(noisyElectrons>fullWell) = fullWell;

% Convert electrons to DN
imageDN = expectedElectrons .* gain;
noisyImageDN = noisyElectrons .* gain;

end
